#!/bin/sh
if [ $# -ge 3 ]  && [ $1 = alias ] ; then
    cmd=$2
    shift 2
    cat .aka | grep -v "alias $cmd=" > .aka
    echo "alias $cmd='$*'" >> .aka
    exit 0
fi
if [ -e .aka ] ; then
    . ./.aka
fi
eval $*
